
const vocabulary = [
    // 五年级上册 Unit 1
    { word: "young", translation: "年轻的", explanation: "形容年龄小或看起来年轻", pronunciation: "/jʌŋ/", category: "形容词", volume: "上册" },
    { word: "funny", translation: "滑稽可笑的", explanation: "令人发笑的，有趣的", pronunciation: "/ˈfʌni/", category: "形容词", volume: "上册" },
    { word: "tall", translation: "高的", explanation: "身高很高", pronunciation: "/tɔːl/", category: "形容词", volume: "上册" },
    { word: "strong", translation: "强壮的", explanation: "身体强健有力", pronunciation: "/strɒŋ/", category: "形容词", volume: "上册" },
    { word: "kind", translation: "和蔼的、亲切的", explanation: "对人友善温和", pronunciation: "/kaɪnd/", category: "形容词", volume: "上册" },
    { word: "old", translation: "年老的", explanation: "年龄大的", pronunciation: "/əʊld/", category: "形容词", volume: "上册" },
    { word: "short", translation: "矮的", explanation: "身高不高", pronunciation: "/ʃɔːt/", category: "形容词", volume: "上册" },
    { word: "thin", translation: "瘦的", explanation: "身体不胖", pronunciation: "/θɪn/", category: "形容词", volume: "上册" },
    { word: "Mr", translation: "先生", explanation: "对男性的尊称", pronunciation: "/ˈmɪstə(r)/", category: "称谓", volume: "上册" },
    { word: "like", translation: "像、喜欢", explanation: "相似或者喜爱", pronunciation: "/laɪk/", category: "动词", volume: "上册" },
    { word: "strict", translation: "严格的", explanation: "要求严厉", pronunciation: "/strɪkt/", category: "形容词", volume: "上册" },
    { word: "smart", translation: "聪明的、巧妙的", explanation: "智慧的，机智的", pronunciation: "/smɑːt/", category: "形容词", volume: "上册" },
    { word: "active", translation: "积极的、活跃的", explanation: "主动的，活泼的", pronunciation: "/ˈæktɪv/", category: "形容词", volume: "上册" },
    { word: "quiet", translation: "安静的、文静的", explanation: "不吵闹的", pronunciation: "/ˈkwaɪət/", category: "形容词", volume: "上册" },
    { word: "very", translation: "很、非常", explanation: "程度副词", pronunciation: "/ˈveri/", category: "副词", volume: "上册" },
    { word: "but", translation: "但是", explanation: "表示转折的连词", pronunciation: "/bʌt/", category: "连词", volume: "上册" },
    { word: "principal", translation: "校长", explanation: "学校的负责人", pronunciation: "/ˈprɪnsəpl/", category: "职业", volume: "上册" },
    
    // 五年级上册 Unit 2
    { word: "Monday", translation: "星期一", explanation: "一周的第一天", pronunciation: "/ˈmʌndeɪ/", category: "时间", volume: "上册" },
    { word: "Tuesday", translation: "星期二", explanation: "一周的第二天", pronunciation: "/ˈtjuːzdeɪ/", category: "时间", volume: "上册" },
    { word: "Wednesday", translation: "星期三", explanation: "一周的第三天", pronunciation: "/ˈwenzdeɪ/", category: "时间", volume: "上册" },
    { word: "Thursday", translation: "星期四", explanation: "一周的第四天", pronunciation: "/ˈθɜːzdeɪ/", category: "时间", volume: "上册" },
    { word: "Friday", translation: "星期五", explanation: "一周的第五天", pronunciation: "/ˈfraɪdeɪ/", category: "时间", volume: "上册" },
    { word: "Saturday", translation: "星期六", explanation: "一周的第六天", pronunciation: "/ˈsætədeɪ/", category: "时间", volume: "上册" },
    { word: "Sunday", translation: "星期天", explanation: "一周的第七天", pronunciation: "/ˈsʌndeɪ/", category: "时间", volume: "上册" },
    { word: "day", translation: "天", explanation: "一天的时间", pronunciation: "/deɪ/", category: "时间", volume: "上册" },
    { word: "have", translation: "有、吃", explanation: "拥有或进食", pronunciation: "/hæv/", category: "动词", volume: "上册" },
    { word: "on", translation: "在...时候", explanation: "表示时间或位置的介词", pronunciation: "/ɒn/", category: "介词", volume: "上册" },
    { word: "do homework", translation: "做作业", explanation: "完成学校布置的作业", pronunciation: "/duː ˈhəʊmwɜːk/", category: "动作", volume: "上册" },
    { word: "watch TV", translation: "看电视", explanation: "观看电视节目", pronunciation: "/wɒtʃ ˌtiːˈviː/", category: "动作", volume: "上册" },
    { word: "read books", translation: "读书", explanation: "阅读书籍", pronunciation: "/riːd bʊks/", category: "动作", volume: "上册" },
    
    // 五年级上册 Unit 3
    { word: "eggplant", translation: "茄子", explanation: "紫色的蔬菜", pronunciation: "/ˈeɡplɑːnt/", category: "食物", volume: "上册" },
    { word: "fish", translation: "鱼", explanation: "生活在水中的动物", pronunciation: "/fɪʃ/", category: "食物", volume: "上册" },
    { word: "green beans", translation: "青豆", explanation: "绿色的豆类蔬菜", pronunciation: "/ɡriːn biːnz/", category: "食物", volume: "上册" },
    { word: "tofu", translation: "豆腐", explanation: "用大豆制成的食品", pronunciation: "/ˈtəʊfuː/", category: "食物", volume: "上册" },
    { word: "potato", translation: "土豆", explanation: "常见的根茎类蔬菜", pronunciation: "/pəˈteɪtəʊ/", category: "食物", volume: "上册" },
    { word: "tomato", translation: "西红柿", explanation: "红色的蔬菜水果", pronunciation: "/təˈmɑːtəʊ/", category: "食物", volume: "上册" },
    { word: "for", translation: "为", explanation: "表示目的的介词", pronunciation: "/fɔː(r)/", category: "介词", volume: "上册" },
    { word: "lunch", translation: "中餐", explanation: "中午的一餐", pronunciation: "/lʌntʃ/", category: "食物", volume: "上册" },
    { word: "we", translation: "我们", explanation: "第一人称复数代词", pronunciation: "/wiː/", category: "代词", volume: "上册" },
    { word: "tasty", translation: "好吃的", explanation: "味道很好", pronunciation: "/ˈteɪsti/", category: "形容词", volume: "上册" },
    { word: "sweet", translation: "甜的", explanation: "有甜味的", pronunciation: "/swiːt/", category: "形容词", volume: "上册" },
    { word: "sour", translation: "酸的", explanation: "有酸味的", pronunciation: "/ˈsaʊə(r)/", category: "形容词", volume: "上册" },
    { word: "fresh", translation: "新鲜的", explanation: "刚采摘的，不陈旧的", pronunciation: "/freʃ/", category: "形容词", volume: "上册" },
    { word: "salty", translation: "咸的", explanation: "有咸味的", pronunciation: "/ˈsɔːlti/", category: "形容词", volume: "上册" },
    { word: "favourite", translation: "最喜欢的", explanation: "最爱的", pronunciation: "/ˈfeɪvərɪt/", category: "形容词", volume: "上册" },
    { word: "fruit", translation: "水果", explanation: "植物的果实", pronunciation: "/fruːt/", category: "食物", volume: "上册" },
    { word: "grape", translation: "葡萄", explanation: "紫色或绿色的小圆果实", pronunciation: "/ɡreɪp/", category: "食物", volume: "上册" },
    
    // 五年级上册 Unit 4
    { word: "cook the meals", translation: "做饭", explanation: "准备食物", pronunciation: "/kʊk ðə miːlz/", category: "动作", volume: "上册" },
    { word: "water the flowers", translation: "浇花", explanation: "给花浇水", pronunciation: "/ˈwɔːtə(r) ðə ˈflaʊəz/", category: "动作", volume: "上册" },
    { word: "sweep the floor", translation: "扫地", explanation: "清扫地面", pronunciation: "/swiːp ðə flɔː(r)/", category: "动作", volume: "上册" },
    { word: "clean the bedroom", translation: "打扫卧室", explanation: "整理卧室", pronunciation: "/kliːn ðə ˈbedruːm/", category: "动作", volume: "上册" },
    { word: "make the bed", translation: "铺床", explanation: "整理床铺", pronunciation: "/meɪk ðə bed/", category: "动作", volume: "上册" },
    { word: "set the table", translation: "摆饭桌", explanation: "准备餐桌", pronunciation: "/set ðə ˈteɪbl/", category: "动作", volume: "上册" },
    { word: "wash the clothes", translation: "洗衣服", explanation: "清洗衣物", pronunciation: "/wɒʃ ðə kləʊðz/", category: "动作", volume: "上册" },
    { word: "do the dishes", translation: "洗碗碟", explanation: "清洗餐具", pronunciation: "/duː ðə ˈdɪʃɪz/", category: "动作", volume: "上册" },
    { word: "use a computer", translation: "使用计算机", explanation: "操作电脑", pronunciation: "/juːz ə kəmˈpjuːtə(r)/", category: "动作", volume: "上册" },
    
    // 五年级上册 Unit 5
    { word: "curtain", translation: "窗帘", explanation: "挂在窗户上的布", pronunciation: "/ˈkɜːtn/", category: "物品", volume: "上册" },
    { word: "trash bin", translation: "垃圾箱", explanation: "装垃圾的容器", pronunciation: "/træʃ bɪn/", category: "物品", volume: "上册" },
    { word: "closet", translation: "壁橱", explanation: "嵌在墙里的柜子", pronunciation: "/ˈklɒzɪt/", category: "物品", volume: "上册" },
    { word: "mirror", translation: "镜子", explanation: "能照出影像的玻璃", pronunciation: "/ˈmɪrə(r)/", category: "物品", volume: "上册" },
    { word: "end table", translation: "床头柜", explanation: "放在床边的小桌子", pronunciation: "/end ˈteɪbl/", category: "物品", volume: "上册" },
    { word: "bedroom", translation: "卧室", explanation: "睡觉的房间", pronunciation: "/ˈbedruːm/", category: "地点", volume: "上册" },
    { word: "kitchen", translation: "厨房", explanation: "做饭的房间", pronunciation: "/ˈkɪtʃɪn/", category: "地点", volume: "上册" },
    { word: "bathroom", translation: "卫生间", explanation: "洗澡和如厕的房间", pronunciation: "/ˈbɑːθruːm/", category: "地点", volume: "上册" },
    { word: "living room", translation: "客厅", explanation: "会客和休息的房间", pronunciation: "/ˈlɪvɪŋ ruːm/", category: "地点", volume: "上册" },
    { word: "in", translation: "在里面", explanation: "表示位置的介词", pronunciation: "/ɪn/", category: "介词", volume: "上册" },
    { word: "on", translation: "在上面", explanation: "表示位置的介词", pronunciation: "/ɒn/", category: "介词", volume: "上册" },
    { word: "under", translation: "在下面", explanation: "表示位置的介词", pronunciation: "/ˈʌndə(r)/", category: "介词", volume: "上册" },
    { word: "near", translation: "在旁边", explanation: "表示位置接近", pronunciation: "/nɪə(r)/", category: "介词", volume: "上册" },
    { word: "behind", translation: "在后边", explanation: "表示位置在后面", pronunciation: "/bɪˈhaɪnd/", category: "介词", volume: "上册" },
    { word: "clothes", translation: "衣服", explanation: "穿在身上的物品", pronunciation: "/kləʊðz/", category: "物品", volume: "上册" },
    
    // 五年级上册 Unit 6
    { word: "river", translation: "河流", explanation: "流动的水道", pronunciation: "/ˈrɪvə(r)/", category: "自然", volume: "上册" },
    { word: "flower", translation: "花", explanation: "植物的花朵", pronunciation: "/ˈflaʊə(r)/", category: "自然", volume: "上册" },
    { word: "grass", translation: "草", explanation: "绿色的小植物", pronunciation: "/ɡrɑːs/", category: "自然", volume: "上册" },
    { word: "lake", translation: "湖泊", explanation: "大片的淡水", pronunciation: "/leɪk/", category: "自然", volume: "上册" },
    { word: "forest", translation: "森林", explanation: "大片的树木", pronunciation: "/ˈfɒrɪst/", category: "自然", volume: "上册" },
    { word: "path", translation: "路", explanation: "小径，道路", pronunciation: "/pɑːθ/", category: "地点", volume: "上册" },
    { word: "park", translation: "公园", explanation: "供人休闲的场所", pronunciation: "/pɑːk/", category: "地点", volume: "上册" },
    { word: "picture", translation: "照片", explanation: "图像，相片", pronunciation: "/ˈpɪktʃə(r)/", category: "物品", volume: "上册" },
    { word: "house", translation: "房子", explanation: "居住的建筑", pronunciation: "/haʊs/", category: "地点", volume: "上册" },
    { word: "bridge", translation: "桥", explanation: "跨越河流的建筑", pronunciation: "/brɪdʒ/", category: "地点", volume: "上册" },
    { word: "tree", translation: "树", explanation: "高大的植物", pronunciation: "/triː/", category: "自然", volume: "上册" },
    { word: "road", translation: "公路", explanation: "供车辆行驶的道路", pronunciation: "/rəʊd/", category: "地点", volume: "上册" },
    { word: "building", translation: "建筑物", explanation: "人工建造的结构", pronunciation: "/ˈbɪldɪŋ/", category: "地点", volume: "上册" },
    { word: "clean", translation: "干净的", explanation: "没有污垢的", pronunciation: "/kliːn/", category: "形容词", volume: "上册" },
    
    // 五年级下册 Unit 1
    { word: "eat breakfast", translation: "吃早饭", explanation: "进食早餐", pronunciation: "/iːt ˈbrekfəst/", category: "动作", volume: "下册" },
    { word: "play sports", translation: "进行体育活动", explanation: "参加运动", pronunciation: "/pleɪ spɔːts/", category: "动作", volume: "下册" },
    { word: "exercise", translation: "练习；锻炼", explanation: "身体活动或学习练习", pronunciation: "/ˈeksəsaɪz/", category: "动作", volume: "下册" },
    { word: "do morning exercises", translation: "晨练", explanation: "早晨的体育锻炼", pronunciation: "/duː ˈmɔːnɪŋ ˈeksəsaɪzɪz/", category: "动作", volume: "下册" },
    { word: "eat dinner", translation: "吃晚饭", explanation: "进食晚餐", pronunciation: "/iːt ˈdɪnə(r)/", category: "动作", volume: "下册" },
    { word: "clean my room", translation: "打扫我的房间", explanation: "整理自己的房间", pronunciation: "/kliːn maɪ ruːm/", category: "动作", volume: "下册" },
    { word: "go for a walk", translation: "散步", explanation: "外出步行", pronunciation: "/ɡəʊ fɔːr ə wɔːk/", category: "动作", volume: "下册" },
    { word: "go shopping", translation: "(去)买东西", explanation: "外出购物", pronunciation: "/ɡəʊ ˈʃɒpɪŋ/", category: "动作", volume: "下册" },
    { word: "take", translation: "拿；拿走；做；服用；乘坐；花费", explanation: "多种含义的动词", pronunciation: "/teɪk/", category: "动词", volume: "下册" },
    { word: "dancing", translation: "跳舞；舞蹈", explanation: "舞蹈活动", pronunciation: "/ˈdɑːnsɪŋ/", category: "动作", volume: "下册" },
    { word: "take a dancing class", translation: "去舞蹈班", explanation: "参加舞蹈课程", pronunciation: "/teɪk ə ˈdɑːnsɪŋ klɑːs/", category: "动作", volume: "下册" },
    { word: "when", translation: "当…的时候；什么时候，何时", explanation: "时间疑问词或连词", pronunciation: "/wen/", category: "疑问词", volume: "下册" },
    { word: "after", translation: "在…之后", explanation: "时间介词", pronunciation: "/ˈɑːftə(r)/", category: "介词", volume: "下册" },
    { word: "start", translation: "开始，着手；出发", explanation: "开始做某事", pronunciation: "/stɑːt/", category: "动词", volume: "下册" },
    { word: "usually", translation: "通常，经常", explanation: "频率副词", pronunciation: "/ˈjuːʒuəli/", category: "副词", volume: "下册" },
    { word: "Spain", translation: "西班牙", explanation: "欧洲国家名", pronunciation: "/speɪn/", category: "地名", volume: "下册" },
    { word: "late", translation: "晚的，迟的", explanation: "时间晚或迟到", pronunciation: "/leɪt/", category: "形容词", volume: "下册" },
    { word: "A.M.", translation: "午前，上午", explanation: "上午时间标记", pronunciation: "/ˌeɪ ˈem/", category: "时间", volume: "下册" },
    { word: "P.M.", translation: "下午，午后", explanation: "下午时间标记", pronunciation: "/ˌpiː ˈem/", category: "时间", volume: "下册" },
    { word: "why", translation: "为什么", explanation: "原因疑问词", pronunciation: "/waɪ/", category: "疑问词", volume: "下册" },
    { word: "shop", translation: "买东西；商店", explanation: "购物或商店", pronunciation: "/ʃɒp/", category: "动词", volume: "下册" },
    { word: "work", translation: "工作，劳动", explanation: "职业活动", pronunciation: "/wɜːk/", category: "动词", volume: "下册" },
    { word: "last", translation: "最近刚过去的；最后的", explanation: "时间或顺序的最后", pronunciation: "/lɑːst/", category: "形容词", volume: "下册" },
    { word: "sound", translation: "听起来；声音", explanation: "听觉感受或声响", pronunciation: "/saʊnd/", category: "动词", volume: "下册" },
    { word: "also", translation: "也，同样；而且，还", explanation: "表示同样或另外", pronunciation: "/ˈɔːlsəʊ/", category: "副词", volume: "下册" },
    { word: "busy", translation: "忙(碌)的", explanation: "有很多事情要做", pronunciation: "/ˈbɪzi/", category: "形容词", volume: "下册" },
    { word: "need", translation: "需要，必须", explanation: "必要性", pronunciation: "/niːd/", category: "动词", volume: "下册" },
    { word: "play", translation: "玩；打(球)；游戏；播放", explanation: "娱乐活动", pronunciation: "/pleɪ/", category: "动词", volume: "下册" },
    { word: "letter", translation: "信；字母", explanation: "书信或字母符号", pronunciation: "/ˈletə(r)/", category: "物品", volume: "下册" },
    { word: "live", translation: "生活；居住；活着", explanation: "生存状态", pronunciation: "/lɪv/", category: "动词", volume: "下册" },
    { word: "island", translation: "岛", explanation: "被水包围的陆地", pronunciation: "/ˈaɪlənd/", category: "地理", volume: "下册" },
    { word: "always", translation: "总是；一直；永远", explanation: "频率副词，表示一直", pronunciation: "/ˈɔːlweɪz/", category: "副词", volume: "下册" },
    { word: "cave", translation: "洞穴", explanation: "天然的洞", pronunciation: "/keɪv/", category: "地理", volume: "下册" },
    { word: "go swimming", translation: "去游泳", explanation: "进行游泳活动", pronunciation: "/ɡəʊ ˈswɪmɪŋ/", category: "动作", volume: "下册" },
    { word: "win", translation: "获胜，赢得", explanation: "在比赛中取胜", pronunciation: "/wɪn/", category: "动词", volume: "下册" },
    
    // 五年级下册 Unit 2
    { word: "spring", translation: "春天，春季", explanation: "一年四季之一", pronunciation: "/sprɪŋ/", category: "季节", volume: "下册" },
    { word: "summer", translation: "夏天，夏季", explanation: "一年四季之一", pronunciation: "/ˈsʌmə(r)/", category: "季节", volume: "下册" },
    { word: "autumn", translation: "秋天，秋季", explanation: "一年四季之一", pronunciation: "/ˈɔːtəm/", category: "季节", volume: "下册" },
    { word: "winter", translation: "冬天，冬季", explanation: "一年四季之一", pronunciation: "/ˈwɪntə(r)/", category: "季节", volume: "下册" },
    { word: "season", translation: "季；季节", explanation: "一年中的时期", pronunciation: "/ˈsiːzn/", category: "时间", volume: "下册" },
    { word: "picnic", translation: "野餐", explanation: "户外用餐", pronunciation: "/ˈpɪknɪk/", category: "活动", volume: "下册" },
    { word: "go on a picnic", translation: "去野餐", explanation: "进行野餐活动", pronunciation: "/ɡəʊ ɒn ə ˈpɪknɪk/", category: "动作", volume: "下册" },
    { word: "pick", translation: "采摘；拾取；挑选", explanation: "选择或采集", pronunciation: "/pɪk/", category: "动词", volume: "下册" },
    { word: "pick apples", translation: "摘苹果", explanation: "采摘苹果", pronunciation: "/pɪk ˈæplz/", category: "动作", volume: "下册" },
    { word: "snowman", translation: "雪人", explanation: "用雪堆成的人形", pronunciation: "/ˈsnəʊmæn/", category: "物品", volume: "下册" },
    { word: "make a snowman", translation: "堆雪人", explanation: "用雪制作雪人", pronunciation: "/meɪk ə ˈsnəʊmæn/", category: "动作", volume: "下册" },
    { word: "which", translation: "那(哪)一个；那(哪)一些", explanation: "疑问代词", pronunciation: "/wɪtʃ/", category: "疑问词", volume: "下册" },
    { word: "best", translation: "最好的；最好地，最", explanation: "good和well的最高级", pronunciation: "/best/", category: "形容词", volume: "下册" },
    { word: "snow", translation: "雪；下雪", explanation: "天气现象", pronunciation: "/snəʊ/", category: "自然", volume: "下册" },
    { word: "good job", translation: "干得好", explanation: "表扬用语", pronunciation: "/ɡʊd dʒɒb/", category: "短语", volume: "下册" },
    { word: "because", translation: "因为", explanation: "表示原因的连词", pronunciation: "/bɪˈkɒz/", category: "连词", volume: "下册" },
    { word: "vacation", translation: "假期", explanation: "休假时间", pronunciation: "/vəˈkeɪʃn/", category: "时间", volume: "下册" },
    { word: "all", translation: "全部；全部地；完全", explanation: "表示全部", pronunciation: "/ɔːl/", category: "形容词", volume: "下册" },
    { word: "pink", translation: "粉红色的；桃红色的", explanation: "颜色形容词", pronunciation: "/pɪŋk/", category: "颜色", volume: "下册" },
    { word: "lovely", translation: "美好的，可爱的", explanation: "形容美好", pronunciation: "/ˈlʌvli/", category: "形容词", volume: "下册" },
    { word: "leaf", translation: "(树，菜)叶", explanation: "植物的叶子", pronunciation: "/liːf/", category: "自然", volume: "下册" },
    { word: "fall", translation: "(美)秋季；瀑布；落(下)，降落", explanation: "秋天或下降", pronunciation: "/fɔːl/", category: "季节", volume: "下册" },
    { word: "paint", translation: "油漆；涂漆；画；绘画", explanation: "绘画或涂色", pronunciation: "/peɪnt/", category: "动词", volume: "下册" },
    
    // 五年级下册 Unit 3
    { word: "January", translation: "1月", explanation: "一年的第一个月", pronunciation: "/ˈdʒænjuəri/", category: "时间", volume: "下册" },
    { word: "February", translation: "2月", explanation: "一年的第二个月", pronunciation: "/ˈfebruəri/", category: "时间", volume: "下册" },
    { word: "March", translation: "3月", explanation: "一年的第三个月", pronunciation: "/mɑːtʃ/", category: "时间", volume: "下册" },
    { word: "April", translation: "4月", explanation: "一年的第四个月", pronunciation: "/ˈeɪprəl/", category: "时间", volume: "下册" },
    { word: "May", translation: "5月", explanation: "一年的第五个月", pronunciation: "/meɪ/", category: "时间", volume: "下册" },
    { word: "June", translation: "6月", explanation: "一年的第六个月", pronunciation: "/dʒuːn/", category: "时间", volume: "下册" },
    { word: "July", translation: "7月", explanation: "一年的第七个月", pronunciation: "/dʒuˈlaɪ/", category: "时间", volume: "下册" },
    { word: "August", translation: "8月", explanation: "一年的第八个月", pronunciation: "/ˈɔːɡəst/", category: "时间", volume: "下册" },
    { word: "September", translation: "9月", explanation: "一年的第九个月", pronunciation: "/sepˈtembə(r)/", category: "时间", volume: "下册" },
    { word: "October", translation: "10月", explanation: "一年的第十个月", pronunciation: "/ɒkˈtəʊbə(r)/", category: "时间", volume: "下册" },
    { word: "November", translation: "11月", explanation: "一年的第十一个月", pronunciation: "/nəʊˈvembə(r)/", category: "时间", volume: "下册" },
    { word: "December", translation: "12月", explanation: "一年的第十二个月", pronunciation: "/dɪˈsembə(r)/", category: "时间", volume: "下册" },
    { word: "few", translation: "很少的；少数的", explanation: "数量少", pronunciation: "/fjuː/", category: "形容词", volume: "下册" },
    { word: "a few", translation: "一些，少量", explanation: "少数几个", pronunciation: "/ə fjuː/", category: "短语", volume: "下册" },
    { word: "thing", translation: "东西；物品，用品；事情，事件", explanation: "物体或事情", pronunciation: "/θɪŋ/", category: "名词", volume: "下册" },
    { word: "meet", translation: "遇见，见到；会；集会", explanation: "相遇或聚会", pronunciation: "/miːt/", category: "动词", volume: "下册" },
    { word: "sports meet", translation: "运动会", explanation: "体育比赛活动", pronunciation: "/spɔːts miːt/", category: "活动", volume: "下册" },
    { word: "Easter", translation: "复活节", explanation: "基督教节日", pronunciation: "/ˈiːstə(r)/", category: "节日", volume: "下册" },
    { word: "trip", translation: "旅行，旅程", explanation: "外出旅游", pronunciation: "/trɪp/", category: "活动", volume: "下册" },
    { word: "year", translation: "年", explanation: "时间单位", pronunciation: "/jɪə(r)/", category: "时间", volume: "下册" },
    { word: "plant", translation: "种植，播种；植物；工厂", explanation: "植物或种植", pronunciation: "/plɑːnt/", category: "动词", volume: "下册" },
    { word: "contest", translation: "竞赛，比赛", explanation: "比赛活动", pronunciation: "/ˈkɒntest/", category: "活动", volume: "下册" },
    { word: "the Great Wall", translation: "长城", explanation: "中国著名建筑", pronunciation: "/ðə ɡreɪt wɔːl/", category: "地名", volume: "下册" },
    { word: "national", translation: "国家的；全国性的；民族的", explanation: "国家层面的", pronunciation: "/ˈnæʃnəl/", category: "形容词", volume: "下册" },
    { word: "National Day", translation: "国庆节", explanation: "国家节日", pronunciation: "/ˈnæʃnəl deɪ/", category: "节日", volume: "下册" },
    { word: "American", translation: "美国人；美国的；美国人的", explanation: "美国相关", pronunciation: "/əˈmerɪkən/", category: "国籍", volume: "下册" },
    { word: "Thanksgiving", translation: "感恩节", explanation: "美国节日", pronunciation: "/ˈθæŋksɡɪvɪŋ/", category: "节日", volume: "下册" },
    { word: "Christmas", translation: "圣诞节", explanation: "基督教节日", pronunciation: "/ˈkrɪsməs/", category: "节日", volume: "下册" },
    { word: "holiday", translation: "假日；节日", explanation: "休息日", pronunciation: "/ˈhɒlədeɪ/", category: "时间", volume: "下册" },
    { word: "game", translation: "游戏；比赛", explanation: "娱乐活动", pronunciation: "/ɡeɪm/", category: "活动", volume: "下册" },
    { word: "roll", translation: "滚动", explanation: "转动", pronunciation: "/rəʊl/", category: "动词", volume: "下册" },
    { word: "look for", translation: "寻找", explanation: "搜寻", pronunciation: "/lʊk fɔː(r)/", category: "动作", volume: "下册" },
    { word: "chocolate", translation: "巧克力", explanation: "甜食", pronunciation: "/ˈtʃɒklət/", category: "食物", volume: "下册" },
    { word: "bunny", translation: "小兔子", explanation: "兔子的昵称", pronunciation: "/ˈbʌni/", category: "动物", volume: "下册" },
    { word: "RSVP", translation: "请回复", explanation: "邀请函用语", pronunciation: "/ˌɑːr es viː ˈpiː/", category: "缩写", volume: "下册" },
    { word: "by", translation: "在...之前；被；由", explanation: "介词，多种用法", pronunciation: "/baɪ/", category: "介词", volume: "下册" },
        
        // 五年级下册 Unit 4
        { word: "mine", translation: "我的", explanation: "名词性物主代词", pronunciation: "/maɪn/", category: "代词", volume: "下册" },
        { word: "yours", translation: "你(们)的", explanation: "名词性物主代词", pronunciation: "/jɔːz/", category: "代词", volume: "下册" },
        { word: "his", translation: "他的", explanation: "名词性物主代词", pronunciation: "/hɪz/", category: "代词", volume: "下册" },
        { word: "hers", translation: "她的", explanation: "名词性物主代词", pronunciation: "/hɜːz/", category: "代词", volume: "下册" },
        { word: "theirs", translation: "他们的；她们的；它们的", explanation: "名词性物主代词", pronunciation: "/ðeəz/", category: "代词", volume: "下册" },
        { word: "ours", translation: "我们的", explanation: "名词性物主代词", pronunciation: "/aʊəz/", category: "代词", volume: "下册" },
        { word: "climbing", translation: "攀登；攀爬", explanation: "爬山或攀爬活动", pronunciation: "/ˈklaɪmɪŋ/", category: "动作", volume: "下册" },
        { word: "eating", translation: "吃", explanation: "进食动作", pronunciation: "/ˈiːtɪŋ/", category: "动作", volume: "下册" },
        { word: "playing", translation: "玩耍", explanation: "游戏或娱乐活动", pronunciation: "/ˈpleɪɪŋ/", category: "动作", volume: "下册" },
        { word: "jumping", translation: "跳", explanation: "跳跃动作", pronunciation: "/ˈdʒʌmpɪŋ/", category: "动作", volume: "下册" },
        { word: "drinking", translation: "喝(水)", explanation: "饮用液体", pronunciation: "/ˈdrɪŋkɪŋ/", category: "动作", volume: "下册" },
        { word: "sleeping", translation: "睡觉", explanation: "休息睡眠", pronunciation: "/ˈsliːpɪŋ/", category: "动作", volume: "下册" },
        { word: "each", translation: "每一；各个", explanation: "表示每个", pronunciation: "/iːtʃ/", category: "形容词", volume: "下册" },
        { word: "other", translation: "其他的", explanation: "别的，其他的", pronunciation: "/ˈʌðə(r)/", category: "形容词", volume: "下册" },
        { word: "each other", translation: "相互", explanation: "彼此，互相", pronunciation: "/iːtʃ ˈʌðə(r)/", category: "短语", volume: "下册" },
        { word: "excited", translation: "兴奋的；激动的", explanation: "情绪激动", pronunciation: "/ɪkˈsaɪtɪd/", category: "形容词", volume: "下册" },
        { word: "like", translation: "像...一样", explanation: "相似或比较", pronunciation: "/laɪk/", category: "介词", volume: "下册" },
        
        // 五年级下册 Unit 5
        { word: "doing", translation: "做(事情)", explanation: "进行某种活动", pronunciation: "/ˈduːɪŋ/", category: "动作", volume: "下册" },
        { word: "morning", translation: "早晨；上午", explanation: "一天的早期时间", pronunciation: "/ˈmɔːnɪŋ/", category: "时间", volume: "下册" },
        { word: "exercises", translation: "活动；运动；练习", explanation: "体育锻炼或学习练习", pronunciation: "/ˈeksəsaɪzɪz/", category: "动作", volume: "下册" },
        { word: "having", translation: "吃；有", explanation: "拥有或进食", pronunciation: "/ˈhævɪŋ/", category: "动作", volume: "下册" },
        { word: "class", translation: "课；班级", explanation: "上课或班级", pronunciation: "/klɑːs/", category: "学习", volume: "下册" },
        { word: "listening", translation: "听", explanation: "用耳朵接收声音", pronunciation: "/ˈlɪsnɪŋ/", category: "动作", volume: "下册" },
        { word: "music", translation: "音乐", explanation: "声音艺术", pronunciation: "/ˈmjuːzɪk/", category: "艺术", volume: "下册" },
        { word: "listening to music", translation: "听音乐", explanation: "欣赏音乐", pronunciation: "/ˈlɪsnɪŋ tuː ˈmjuːzɪk/", category: "动作", volume: "下册" },
        { word: "reading", translation: "读", explanation: "阅读文字", pronunciation: "/ˈriːdɪŋ/", category: "动作", volume: "下册" },
        { word: "book", translation: "书", explanation: "印刷的读物", pronunciation: "/bʊk/", category: "物品", volume: "下册" },
        { word: "reading a book", translation: "看书", explanation: "阅读书籍", pronunciation: "/ˈriːdɪŋ ə bʊk/", category: "动作", volume: "下册" },
        { word: "what", translation: "什么", explanation: "疑问代词", pronunciation: "/wɒt/", category: "疑问词", volume: "下册" },
        { word: "cooking", translation: "烹饪；做饭", explanation: "制作食物", pronunciation: "/ˈkʊkɪŋ/", category: "动作", volume: "下册" },
        { word: "dinner", translation: "晚餐；正餐", explanation: "一天的主要餐食", pronunciation: "/ˈdɪnə(r)/", category: "食物", volume: "下册" },
        { word: "cooking dinner", translation: "做晚饭", explanation: "准备晚餐", pronunciation: "/ˈkʊkɪŋ ˈdɪnə(r)/", category: "动作", volume: "下册" },
        { word: "reading a newspaper", translation: "看报纸", explanation: "阅读新闻报纸", pronunciation: "/ˈriːdɪŋ ə ˈnjuːzpeɪpə(r)/", category: "动作", volume: "下册" },
        { word: "mom", translation: "妈妈", explanation: "母亲的昵称", pronunciation: "/mɒm/", category: "家庭", volume: "下册" },
        { word: "grandpa", translation: "爷爷；外公", explanation: "祖父的昵称", pronunciation: "/ˈɡrænpɑː/", category: "家庭", volume: "下册" },
        { word: "study", translation: "书房", explanation: "学习的房间", pronunciation: "/ˈstʌdi/", category: "地点", volume: "下册" },
        
        // 五年级下册 Unit 6
        { word: "keep", translation: "保持某种状态", explanation: "维持状态", pronunciation: "/kiːp/", category: "动词", volume: "下册" },
        { word: "keep to the right", translation: "靠右", explanation: "保持在右侧", pronunciation: "/kiːp tuː ðə raɪt/", category: "短语", volume: "下册" },
        { word: "keep your desk clean", translation: "保持你的课桌干净", explanation: "维持桌面整洁", pronunciation: "/kiːp jɔː(r) desk kliːn/", category: "短语", volume: "下册" },
        { word: "talk", translation: "讲话；谈话", explanation: "说话交流", pronunciation: "/tɔːk/", category: "动词", volume: "下册" },
        { word: "quietly", translation: "小声地", explanation: "安静地", pronunciation: "/ˈkwaɪətli/", category: "副词", volume: "下册" },
        { word: "talk quietly", translation: "小声讲话", explanation: "轻声说话", pronunciation: "/tɔːk ˈkwaɪətli/", category: "短语", volume: "下册" },
        { word: "turn", translation: "顺序", explanation: "轮流的次序", pronunciation: "/tɜːn/", category: "名词", volume: "下册" },
        { word: "take turns", translation: "按顺序来", explanation: "轮流进行", pronunciation: "/teɪk tɜːnz/", category: "短语", volume: "下册" },
        { word: "bamboo", translation: "竹子", explanation: "一种植物", pronunciation: "/bæmˈbuː/", category: "植物", volume: "下册" },
        { word: "its", translation: "它的", explanation: "物主代词", pronunciation: "/ɪts/", category: "代词", volume: "下册" },
        { word: "show", translation: "给...看", explanation: "展示给别人", pronunciation: "/ʃəʊ/", category: "动词", volume: "下册" },
        { word: "anything", translation: "任何事物", explanation: "任何东西", pronunciation: "/ˈeniθɪŋ/", category: "代词", volume: "下册" },
        { word: "else", translation: "另外；其他", explanation: "别的，其他的", pronunciation: "/els/", category: "副词", volume: "下册" },
        { word: "exhibition", translation: "展览", explanation: "展示活动", pronunciation: "/ˌeksɪˈbɪʃn/", category: "活动", volume: "下册" },
        { word: "say", translation: "说；讲", explanation: "用语言表达", pronunciation: "/seɪ/", category: "动词", volume: "下册" },
        { word: "have a look", translation: "看一看", explanation: "观察一下", pronunciation: "/hæv ə lʊk/", category: "短语", volume: "下册" },
        { word: "sushi", translation: "寿司", explanation: "日本料理", pronunciation: "/ˈsuːʃi/", category: "食物", volume: "下册" },
        { word: "teach", translation: "教", explanation: "传授知识", pronunciation: "/tiːtʃ/", category: "动词", volume: "下册" },
        { word: "sure", translation: "当然", explanation: "肯定，确定", pronunciation: "/ʃʊə(r)/", category: "副词", volume: "下册" },
        { word: "Canadian", translation: "加拿大的", explanation: "加拿大相关", pronunciation: "/kəˈneɪdiən/", category: "国籍", volume: "下册" },
        { word: "Spanish", translation: "西班牙的", explanation: "西班牙相关", pronunciation: "/ˈspænɪʃ/", category: "国籍", volume: "下册" },

    // 六年级上册 Unit 1 - How can I get there?
    { word: "science", translation: "科学", explanation: "研究自然现象的学科", pronunciation: "/ˈsaɪəns/", category: "学科", volume: "上册", grade: "六年级" },
    { word: "museum", translation: "博物馆", explanation: "展示文物和艺术品的地方", pronunciation: "/mjuˈziːəm/", category: "地点", volume: "上册", grade: "六年级" },
    { word: "post office", translation: "邮局", explanation: "寄送邮件的地方", pronunciation: "/pəʊst ˈɒfɪs/", category: "地点", volume: "上册", grade: "六年级" },
    { word: "bookstore", translation: "书店", explanation: "卖书的商店", pronunciation: "/ˈbʊkstɔː/", category: "地点", volume: "上册", grade: "六年级" },
    { word: "cinema", translation: "电影院", explanation: "看电影的地方", pronunciation: "/ˈsɪnəmə/", category: "地点", volume: "上册", grade: "六年级" },
    { word: "hospital", translation: "医院", explanation: "治病的地方", pronunciation: "/ˈhɒspɪtl/", category: "地点", volume: "上册", grade: "六年级" },
    { word: "crossing", translation: "十字路口", explanation: "两条路相交的地方", pronunciation: "/ˈkrɒsɪŋ/", category: "地点", volume: "上册", grade: "六年级" },
    { word: "turn", translation: "转弯", explanation: "改变方向", pronunciation: "/tɜːn/", category: "动词", volume: "上册", grade: "六年级" },
    { word: "left", translation: "左；左边", explanation: "方向词", pronunciation: "/left/", category: "方向", volume: "上册", grade: "六年级" },
    { word: "straight", translation: "笔直地", explanation: "直接向前", pronunciation: "/streɪt/", category: "副词", volume: "上册", grade: "六年级" },
    { word: "right", translation: "右；右边", explanation: "方向词", pronunciation: "/raɪt/", category: "方向", volume: "上册", grade: "六年级" },
    { word: "ask", translation: "问", explanation: "提出问题", pronunciation: "/ɑːsk/", category: "动词", volume: "上册", grade: "六年级" },
    { word: "sir", translation: "先生", explanation: "对男性的尊称", pronunciation: "/sɜː/", category: "称谓", volume: "上册", grade: "六年级" },
    { word: "interesting", translation: "有趣的", explanation: "引起兴趣的", pronunciation: "/ˈɪntrɪstɪŋ/", category: "形容词", volume: "上册", grade: "六年级" },
    { word: "Italian", translation: "意大利的", explanation: "意大利相关的", pronunciation: "/ɪˈtæliən/", category: "国籍", volume: "上册", grade: "六年级" },
    { word: "restaurant", translation: "餐馆", explanation: "吃饭的地方", pronunciation: "/ˈrestrɒnt/", category: "地点", volume: "上册", grade: "六年级" },
    { word: "pizza", translation: "比萨饼", explanation: "意大利食物", pronunciation: "/ˈpiːtsə/", category: "食物", volume: "上册", grade: "六年级" },
    { word: "street", translation: "大街；街道", explanation: "城市中的道路", pronunciation: "/striːt/", category: "地点", volume: "上册", grade: "六年级" },
    { word: "get", translation: "到达", explanation: "抵达某地", pronunciation: "/get/", category: "动词", volume: "上册", grade: "六年级" },
    { word: "GPS", translation: "全球定位系统", explanation: "卫星导航系统", pronunciation: "/ˌdʒiː piː ˈes/", category: "科技", volume: "上册", grade: "六年级" },
    { word: "gave", translation: "提供；交给", explanation: "give的过去式", pronunciation: "/geɪv/", category: "动词", volume: "上册", grade: "六年级" },
    { word: "feature", translation: "特点", explanation: "特征，特色", pronunciation: "/ˈfiːtʃə/", category: "名词", volume: "上册", grade: "六年级" },
    { word: "follow", translation: "跟着", explanation: "跟随", pronunciation: "/ˈfɒləʊ/", category: "动词", volume: "上册", grade: "六年级" },
    { word: "far", translation: "远的，遥远的", explanation: "距离很远", pronunciation: "/fɑː/", category: "形容词", volume: "上册", grade: "六年级" },
    { word: "tell", translation: "告诉，讲述", explanation: "说出信息", pronunciation: "/tel/", category: "动词", volume: "上册", grade: "六年级" },

    // 六年级上册 Unit 2 - Ways to go to school
    { word: "on foot", translation: "步行", explanation: "用脚走路", pronunciation: "/ɒn fʊt/", category: "交通方式", volume: "上册", grade: "六年级" },
    { word: "by", translation: "乘", explanation: "表示交通方式", pronunciation: "/baɪ/", category: "介词", volume: "上册", grade: "六年级" },
    { word: "bus", translation: "公共汽车", explanation: "公共交通工具", pronunciation: "/bʌs/", category: "交通工具", volume: "上册", grade: "六年级" },
    { word: "plane", translation: "飞机", explanation: "空中交通工具", pronunciation: "/pleɪn/", category: "交通工具", volume: "上册", grade: "六年级" },
    { word: "taxi", translation: "出租汽车", explanation: "付费乘坐的汽车", pronunciation: "/ˈtæksi/", category: "交通工具", volume: "上册", grade: "六年级" },
    { word: "ship", translation: "（大）船", explanation: "水上交通工具", pronunciation: "/ʃɪp/", category: "交通工具", volume: "上册", grade: "六年级" },
    { word: "subway", translation: "地铁", explanation: "地下铁路", pronunciation: "/ˈsʌbweɪ/", category: "交通工具", volume: "上册", grade: "六年级" },
    { word: "train", translation: "火车", explanation: "铁路交通工具", pronunciation: "/treɪn/", category: "交通工具", volume: "上册", grade: "六年级" },
    { word: "slow", translation: "慢的", explanation: "速度不快", pronunciation: "/sləʊ/", category: "形容词", volume: "上册", grade: "六年级" },
    { word: "down", translation: "减少；降低", explanation: "向下，减少", pronunciation: "/daʊn/", category: "副词", volume: "上册", grade: "六年级" },
    { word: "slow down", translation: "慢下来", explanation: "减速", pronunciation: "/sləʊ daʊn/", category: "短语", volume: "上册", grade: "六年级" },
    { word: "stop", translation: "停下来", explanation: "停止移动", pronunciation: "/stɒp/", category: "动词", volume: "上册", grade: "六年级" },
    { word: "Mrs", translation: "夫人", explanation: "对已婚女性的尊称", pronunciation: "/ˈmɪsɪz/", category: "称谓", volume: "上册", grade: "六年级" },
    { word: "early", translation: "早到的", explanation: "时间提前", pronunciation: "/ˈɜːli/", category: "形容词", volume: "上册", grade: "六年级" },
    { word: "helmet", translation: "头盔", explanation: "保护头部的装备", pronunciation: "/ˈhelmɪt/", category: "物品", volume: "上册", grade: "六年级" },
    { word: "must", translation: "必须", explanation: "表示必要性", pronunciation: "/mʌst/", category: "情态动词", volume: "上册", grade: "六年级" },
    { word: "wear", translation: "穿着，佩戴", explanation: "穿戴衣物", pronunciation: "/weə/", category: "动词", volume: "上册", grade: "六年级" },
    { word: "attention", translation: "注意，注意力", explanation: "专心，留意", pronunciation: "/əˈtenʃn/", category: "名词", volume: "上册", grade: "六年级" },
    { word: "pay attention to", translation: "注意", explanation: "专心于", pronunciation: "/peɪ əˈtenʃn tuː/", category: "短语", volume: "上册", grade: "六年级" },
    { word: "traffic", translation: "交通", explanation: "车辆通行", pronunciation: "/ˈtræfɪk/", category: "名词", volume: "上册", grade: "六年级" },
    { word: "traffic lights", translation: "交通信号灯", explanation: "控制交通的灯", pronunciation: "/ˈtræfɪk laɪts/", category: "物品", volume: "上册", grade: "六年级" },
    { word: "Munich", translation: "慕尼黑", explanation: "德国城市", pronunciation: "/ˈmjuːnɪk/", category: "地名", volume: "上册", grade: "六年级" },
    { word: "Germany", translation: "德国", explanation: "欧洲国家", pronunciation: "/ˈdʒɜːməni/", category: "国家", volume: "上册", grade: "六年级" },
    { word: "Alaska", translation: "阿拉斯加州", explanation: "美国州名", pronunciation: "/əˈlæskə/", category: "地名", volume: "上册", grade: "六年级" },
    { word: "sled", translation: "雪橇", explanation: "雪地交通工具", pronunciation: "/sled/", category: "交通工具", volume: "上册", grade: "六年级" },
    { word: "fast", translation: "快的；迅速的", explanation: "速度很快", pronunciation: "/fɑːst/", category: "形容词", volume: "上册", grade: "六年级" },
    { word: "ferry", translation: "轮渡", explanation: "水上交通工具", pronunciation: "/ˈferi/", category: "交通工具", volume: "上册", grade: "六年级" },
    { word: "Papa Westray", translation: "帕帕韦斯特雷岛", explanation: "苏格兰岛屿", pronunciation: "/ˈpɑːpə ˈwestreɪ/", category: "地名", volume: "上册", grade: "六年级" },
    { word: "Scotland", translation: "苏格兰", explanation: "英国的一部分", pronunciation: "/ˈskɒtlənd/", category: "国家", volume: "上册", grade: "六年级" },

    // 六年级上册 Unit 3 - My weekend plan
    { word: "visit", translation: "拜访", explanation: "去看望某人", pronunciation: "/ˈvɪzɪt/", category: "动词", volume: "上册", grade: "六年级" },
    { word: "film", translation: "电影", explanation: "影片", pronunciation: "/fɪlm/", category: "娱乐", volume: "上册", grade: "六年级" },
    { word: "see a film", translation: "看电影", explanation: "观看电影", pronunciation: "/siː ə fɪlm/", category: "活动", volume: "上册", grade: "六年级" },
    { word: "trip", translation: "旅行", explanation: "外出游玩", pronunciation: "/trɪp/", category: "活动", volume: "上册", grade: "六年级" },
    { word: "take a trip", translation: "去旅行", explanation: "进行旅游", pronunciation: "/teɪk ə trɪp/", category: "活动", volume: "上册", grade: "六年级" },
    { word: "supermarket", translation: "超市", explanation: "大型商店", pronunciation: "/ˈsuːpəmɑːkɪt/", category: "地点", volume: "上册", grade: "六年级" },
    { word: "evening", translation: "晚上；傍晚", explanation: "一天的晚间时段", pronunciation: "/ˈiːvnɪŋ/", category: "时间", volume: "上册", grade: "六年级" },
    { word: "tonight", translation: "今夜；今晚", explanation: "今天的晚上", pronunciation: "/təˈnaɪt/", category: "时间", volume: "上册", grade: "六年级" },
    { word: "tomorrow", translation: "明天", explanation: "今天的下一天", pronunciation: "/təˈmɒrəʊ/", category: "时间", volume: "上册", grade: "六年级" },
    { word: "next week", translation: "下周", explanation: "下一个星期", pronunciation: "/nekst wiːk/", category: "时间", volume: "上册", grade: "六年级" },
    { word: "dictionary", translation: "词典", explanation: "查单词的书", pronunciation: "/ˈdɪkʃənri/", category: "学习用品", volume: "上册", grade: "六年级" },
    { word: "comic", translation: "滑稽的；喜剧的", explanation: "有趣的，搞笑的", pronunciation: "/ˈkɒmɪk/", category: "形容词", volume: "上册", grade: "六年级" },
    { word: "comic book", translation: "连环画册", explanation: "漫画书", pronunciation: "/ˈkɒmɪk bʊk/", category: "物品", volume: "上册", grade: "六年级" },
    { word: "word", translation: "单词", explanation: "词汇", pronunciation: "/wɜːd/", category: "语言", volume: "上册", grade: "六年级" },
    { word: "word book", translation: "单词书", explanation: "词汇书", pronunciation: "/wɜːd bʊk/", category: "学习用品", volume: "上册", grade: "六年级" },
    { word: "postcard", translation: "明信片", explanation: "邮寄的卡片", pronunciation: "/ˈpəʊstkɑːd/", category: "物品", volume: "上册", grade: "六年级" },

    // 六年级下册 Unit 1 - How tall are you?
    { word: "younger", translation: "更年轻的", explanation: "年龄更小的", pronunciation: "/ˈjʌŋɡə/", category: "形容词", volume: "下册", grade: "六年级" },
    { word: "older", translation: "更年长的", explanation: "年龄更大的", pronunciation: "/ˈəʊldə/", category: "形容词", volume: "下册", grade: "六年级" },
    { word: "taller", translation: "更高的", explanation: "身高更高的", pronunciation: "/ˈtɔːlə/", category: "形容词", volume: "下册", grade: "六年级" },
    { word: "shorter", translation: "更矮的", explanation: "身高更矮的", pronunciation: "/ˈʃɔːtə/", category: "形容词", volume: "下册", grade: "六年级" },
    { word: "longer", translation: "更长的", explanation: "长度更长的", pronunciation: "/ˈlɒŋɡə/", category: "形容词", volume: "下册", grade: "六年级" },
    { word: "thinner", translation: "更瘦的", explanation: "身材更瘦的", pronunciation: "/ˈθɪnə/", category: "形容词", volume: "下册", grade: "六年级" },
    { word: "heavier", translation: "更重的", explanation: "重量更重的", pronunciation: "/ˈheviə/", category: "形容词", volume: "下册", grade: "六年级" },
    { word: "bigger", translation: "更大的", explanation: "尺寸更大的", pronunciation: "/ˈbɪɡə/", category: "形容词", volume: "下册", grade: "六年级" },
    { word: "smaller", translation: "更小的", explanation: "尺寸更小的", pronunciation: "/ˈsmɔːlə/", category: "形容词", volume: "下册", grade: "六年级" },
    { word: "stronger", translation: "更强壮的", explanation: "力量更强的", pronunciation: "/ˈstrɒŋɡə/", category: "形容词", volume: "下册", grade: "六年级" },
    { word: "dinosaur", translation: "恐龙", explanation: "史前动物", pronunciation: "/ˈdaɪnəsɔː/", category: "动物", volume: "下册", grade: "六年级" },
    { word: "hall", translation: "大厅", explanation: "大房间", pronunciation: "/hɔːl/", category: "地点", volume: "下册", grade: "六年级" },
    { word: "metre", translation: "米", explanation: "长度单位", pronunciation: "/ˈmiːtə/", category: "单位", volume: "下册", grade: "六年级" },
    { word: "than", translation: "比", explanation: "用于比较", pronunciation: "/ðæn/", category: "介词", volume: "下册", grade: "六年级" },
    { word: "both", translation: "两个都", explanation: "两者都", pronunciation: "/bəʊθ/", category: "代词", volume: "下册", grade: "六年级" },
    { word: "kilogram", translation: "千克；公斤", explanation: "重量单位", pronunciation: "/ˈkɪləɡræm/", category: "单位", volume: "下册", grade: "六年级" },
    { word: "countryside", translation: "乡村", explanation: "农村地区", pronunciation: "/ˈkʌntrisaɪd/", category: "地点", volume: "下册", grade: "六年级" },
    { word: "lower", translation: "更低地", explanation: "位置更低", pronunciation: "/ˈləʊə/", category: "形容词", volume: "下册", grade: "六年级" },
    { word: "shadow", translation: "阴影；影子", explanation: "物体遮挡光线形成的暗影", pronunciation: "/ˈʃædəʊ/", category: "自然现象", volume: "下册", grade: "六年级" },
    { word: "smarter", translation: "更聪明的", explanation: "智力更高的", pronunciation: "/ˈsmɑːtə/", category: "形容词", volume: "下册", grade: "六年级" },
    { word: "become", translation: "开始变得；变成", explanation: "变化成为", pronunciation: "/bɪˈkʌm/", category: "动词", volume: "下册", grade: "六年级" },

    // 六年级下册 Unit 2 - Last weekend
    { word: "cleaned", translation: "打扫（过去式）", explanation: "clean的过去式", pronunciation: "/kliːnd/", category: "动词", volume: "下册", grade: "六年级" },
    { word: "stayed", translation: "停留（过去式）", explanation: "stay的过去式", pronunciation: "/steɪd/", category: "动词", volume: "下册", grade: "六年级" },
    { word: "washed", translation: "洗（过去式）", explanation: "wash的过去式", pronunciation: "/wɒʃt/", category: "动词", volume: "下册", grade: "六年级" },
    { word: "watched", translation: "看（过去式）", explanation: "watch的过去式", pronunciation: "/wɒtʃt/", category: "动词", volume: "下册", grade: "六年级" },
    { word: "had", translation: "患病；得病（过去式）", explanation: "have的过去式", pronunciation: "/hæd/", category: "动词", volume: "下册", grade: "六年级" },
    { word: "had a cold", translation: "感冒（过去式）", explanation: "患感冒", pronunciation: "/hæd ə kəʊld/", category: "短语", volume: "下册", grade: "六年级" },
    { word: "slept", translation: "睡觉（过去式）", explanation: "sleep的过去式", pronunciation: "/slept/", category: "动词", volume: "下册", grade: "六年级" },
    { word: "read", translation: "读（过去式）", explanation: "read的过去式", pronunciation: "/red/", category: "动词", volume: "下册", grade: "六年级" },
    { word: "saw", translation: "看见（过去式）", explanation: "see的过去式", pronunciation: "/sɔː/", category: "动词", volume: "下册", grade: "六年级" },
    { word: "last", translation: "上一个的", explanation: "刚过去的", pronunciation: "/lɑːst/", category: "形容词", volume: "下册", grade: "六年级" },
    { word: "yesterday", translation: "昨天", explanation: "今天的前一天", pronunciation: "/ˈjestədeɪ/", category: "时间", volume: "下册", grade: "六年级" },
    { word: "before", translation: "在...之前", explanation: "时间或位置在前", pronunciation: "/bɪˈfɔː/", category: "介词", volume: "下册", grade: "六年级" },
    { word: "drank", translation: "喝（过去式）", explanation: "drink的过去式", pronunciation: "/dræŋk/", category: "动词", volume: "下册", grade: "六年级" },
    { word: "show", translation: "演出", explanation: "表演节目", pronunciation: "/ʃəʊ/", category: "名词", volume: "下册", grade: "六年级" },
    { word: "magazine", translation: "杂志", explanation: "期刊读物", pronunciation: "/ˌmæɡəˈziːn/", category: "物品", volume: "下册", grade: "六年级" },
    { word: "better", translation: "更好的", explanation: "good的比较级", pronunciation: "/ˈbetə/", category: "形容词", volume: "下册", grade: "六年级" },
    { word: "faster", translation: "更快的", explanation: "fast的比较级", pronunciation: "/ˈfɑːstə/", category: "形容词", volume: "下册", grade: "六年级" },
    { word: "hotel", translation: "旅馆", explanation: "住宿的地方", pronunciation: "/həʊˈtel/", category: "地点", volume: "下册", grade: "六年级" },
    { word: "fixed", translation: "修理（过去式）", explanation: "fix的过去式", pronunciation: "/fɪkst/", category: "动词", volume: "下册", grade: "六年级" },
    { word: "broken", translation: "破损的", explanation: "坏了的", pronunciation: "/ˈbrəʊkən/", category: "形容词", volume: "下册", grade: "六年级" },
    { word: "lamp", translation: "台灯", explanation: "照明设备", pronunciation: "/læmp/", category: "物品", volume: "下册", grade: "六年级" },
    { word: "loud", translation: "喧闹的；大声的", explanation: "声音很大", pronunciation: "/laʊd/", category: "形容词", volume: "下册", grade: "六年级" },
    { word: "enjoy", translation: "享受...乐趣；喜爱", explanation: "感到快乐", pronunciation: "/ɪnˈdʒɔɪ/", category: "动词", volume: "下册", grade: "六年级" },
    { word: "stay", translation: "暂住；逗留", explanation: "停留在某地", pronunciation: "/steɪ/", category: "动词", volume: "下册", grade: "六年级" },

    // 六年级上册 Unit 4 - I have a pen pal
    { word: "studies", translation: "学习（第三人称单数）", explanation: "study的第三人称单数形式", pronunciation: "/ˈstʌdiz/", category: "动词", volume: "上册", grade: "六年级" },
    { word: "puzzle", translation: "谜；智力游戏", explanation: "需要思考的游戏", pronunciation: "/ˈpʌzl/", category: "游戏", volume: "上册", grade: "六年级" },
    { word: "hiking", translation: "远足", explanation: "徒步旅行", pronunciation: "/ˈhaɪkɪŋ/", category: "活动", volume: "上册", grade: "六年级" },
    { word: "pen pal", translation: "笔友", explanation: "通信的朋友", pronunciation: "/pen pæl/", category: "人物", volume: "上册", grade: "六年级" },
    { word: "hobby", translation: "业余爱好", explanation: "兴趣爱好", pronunciation: "/ˈhɒbi/", category: "兴趣", volume: "上册", grade: "六年级" },
    { word: "jasmine", translation: "茉莉", explanation: "一种花", pronunciation: "/ˈdʒæzmɪn/", category: "植物", volume: "上册", grade: "六年级" },
    { word: "idea", translation: "想法；主意", explanation: "思考的结果", pronunciation: "/aɪˈdɪə/", category: "抽象概念", volume: "上册", grade: "六年级" },
    { word: "Canberra", translation: "堪培拉", explanation: "澳大利亚首都", pronunciation: "/ˈkænbərə/", category: "地名", volume: "上册", grade: "六年级" },
    { word: "amazing", translation: "令人惊奇的", explanation: "非常棒的", pronunciation: "/əˈmeɪzɪŋ/", category: "形容词", volume: "上册", grade: "六年级" },
    { word: "shall", translation: "表示征求意见", explanation: "用于提建议", pronunciation: "/ʃæl/", category: "助动词", volume: "上册", grade: "六年级" },
    { word: "goal", translation: "射门", explanation: "足球术语", pronunciation: "/ɡəʊl/", category: "体育", volume: "上册", grade: "六年级" },
    { word: "join", translation: "加入", explanation: "参加某个组织", pronunciation: "/dʒɔɪn/", category: "动词", volume: "上册", grade: "六年级" },
    { word: "club", translation: "俱乐部", explanation: "兴趣小组", pronunciation: "/klʌb/", category: "组织", volume: "上册", grade: "六年级" },
    { word: "share", translation: "分享", explanation: "与他人共同享有", pronunciation: "/ʃeə/", category: "动词", volume: "上册", grade: "六年级" },

    // 六年级上册 Unit 5 - What does he do?
    { word: "factory", translation: "工厂", explanation: "生产商品的地方", pronunciation: "/ˈfæktri/", category: "地点", volume: "上册", grade: "六年级" },
    { word: "worker", translation: "工人", explanation: "在工厂工作的人", pronunciation: "/ˈwɜːkə/", category: "职业", volume: "上册", grade: "六年级" },
    { word: "postman", translation: "邮递员", explanation: "送邮件的人", pronunciation: "/ˈpəʊstmən/", category: "职业", volume: "上册", grade: "六年级" },
    { word: "businessman", translation: "商人", explanation: "做生意的人", pronunciation: "/ˈbɪznəsmən/", category: "职业", volume: "上册", grade: "六年级" },
    { word: "police officer", translation: "警察", explanation: "维护治安的人", pronunciation: "/pəˈliːs ˈɒfɪsə/", category: "职业", volume: "上册", grade: "六年级" },
    { word: "fisherman", translation: "渔民", explanation: "捕鱼的人", pronunciation: "/ˈfɪʃəmən/", category: "职业", volume: "上册", grade: "六年级" },
    { word: "scientist", translation: "科学家", explanation: "研究科学的人", pronunciation: "/ˈsaɪəntɪst/", category: "职业", volume: "上册", grade: "六年级" },
    { word: "pilot", translation: "飞行员", explanation: "驾驶飞机的人", pronunciation: "/ˈpaɪlət/", category: "职业", volume: "上册", grade: "六年级" },
    { word: "coach", translation: "教练", explanation: "指导运动的人", pronunciation: "/kəʊtʃ/", category: "职业", volume: "上册", grade: "六年级" },
    { word: "country", translation: "国家", explanation: "政治实体", pronunciation: "/ˈkʌntri/", category: "地理", volume: "上册", grade: "六年级" },
    { word: "head teacher", translation: "校长", explanation: "学校的负责人", pronunciation: "/hed ˈtiːtʃə/", category: "职业", volume: "上册", grade: "六年级" },
    { word: "sea", translation: "大海", explanation: "海洋", pronunciation: "/siː/", category: "自然", volume: "上册", grade: "六年级" },
    { word: "stay healthy", translation: "保持健康", explanation: "维持身体健康", pronunciation: "/steɪ ˈhelθi/", category: "短语", volume: "上册", grade: "六年级" },
    { word: "university", translation: "大学", explanation: "高等教育机构", pronunciation: "/ˌjuːnɪˈvɜːsəti/", category: "教育", volume: "上册", grade: "六年级" },
    { word: "gym", translation: "体育馆", explanation: "运动场所", pronunciation: "/dʒɪm/", category: "地点", volume: "上册", grade: "六年级" },
    { word: "if", translation: "如果", explanation: "表示条件", pronunciation: "/ɪf/", category: "连词", volume: "上册", grade: "六年级" },
    { word: "reporter", translation: "记者", explanation: "报道新闻的人", pronunciation: "/rɪˈpɔːtə/", category: "职业", volume: "上册", grade: "六年级" },
    { word: "use", translation: "使用", explanation: "利用某物", pronunciation: "/juːz/", category: "动词", volume: "上册", grade: "六年级" },
    { word: "type", translation: "打字", explanation: "用键盘输入文字", pronunciation: "/taɪp/", category: "动词", volume: "上册", grade: "六年级" },
    { word: "quickly", translation: "迅速地", explanation: "速度很快地", pronunciation: "/ˈkwɪkli/", category: "副词", volume: "上册", grade: "六年级" },
    { word: "secretary", translation: "秘书", explanation: "办公室助理", pronunciation: "/ˈsekrətri/", category: "职业", volume: "上册", grade: "六年级" },

    // 六年级上册 Unit 6 - How do you feel?
    { word: "angry", translation: "生气的", explanation: "感到愤怒", pronunciation: "/ˈæŋɡri/", category: "情感", volume: "上册", grade: "六年级" },
    { word: "afraid", translation: "害怕", explanation: "感到恐惧", pronunciation: "/əˈfreɪd/", category: "情感", volume: "上册", grade: "六年级" },
    { word: "sad", translation: "难过的", explanation: "感到悲伤", pronunciation: "/sæd/", category: "情感", volume: "上册", grade: "六年级" },
    { word: "worried", translation: "担心的；发愁的", explanation: "感到忧虑", pronunciation: "/ˈwʌrid/", category: "情感", volume: "上册", grade: "六年级" },
    { word: "happy", translation: "高兴的", explanation: "感到快乐", pronunciation: "/ˈhæpi/", category: "情感", volume: "上册", grade: "六年级" },
    { word: "see a doctor", translation: "看病", explanation: "去医院看医生", pronunciation: "/siː ə ˈdɒktə/", category: "活动", volume: "上册", grade: "六年级" },
    { word: "wear", translation: "穿", explanation: "穿着衣服", pronunciation: "/weə/", category: "动词", volume: "上册", grade: "六年级" },
    { word: "more", translation: "更多的", explanation: "数量更大", pronunciation: "/mɔː/", category: "形容词", volume: "上册", grade: "六年级" },
    { word: "deep", translation: "深的", explanation: "距离表面远", pronunciation: "/diːp/", category: "形容词", volume: "上册", grade: "六年级" },
    { word: "breath", translation: "呼吸", explanation: "吸气和呼气", pronunciation: "/breθ/", category: "名词", volume: "上册", grade: "六年级" },
    { word: "take a deep breath", translation: "深深吸一口气", explanation: "深呼吸", pronunciation: "/teɪk ə diːp breθ/", category: "短语", volume: "上册", grade: "六年级" },
    { word: "count", translation: "数数", explanation: "按顺序说数字", pronunciation: "/kaʊnt/", category: "动词", volume: "上册", grade: "六年级" },
    { word: "count to ten", translation: "数到十", explanation: "从一数到十", pronunciation: "/kaʊnt tə ten/", category: "短语", volume: "上册", grade: "六年级" },
    { word: "chase", translation: "追赶", explanation: "跟在后面跑", pronunciation: "/tʃeɪs/", category: "动词", volume: "上册", grade: "六年级" },
    { word: "mice", translation: "老鼠（复数）", explanation: "mouse的复数形式", pronunciation: "/maɪs/", category: "动物", volume: "上册", grade: "六年级" },
    { word: "bad", translation: "邪恶的；坏的", explanation: "不好的", pronunciation: "/bæd/", category: "形容词", volume: "上册", grade: "六年级" },
    { word: "hurt", translation: "（使）受伤", explanation: "造成伤害", pronunciation: "/hɜːt/", category: "动词", volume: "上册", grade: "六年级" },
    { word: "ill", translation: "有病；不舒服", explanation: "身体不健康", pronunciation: "/ɪl/", category: "形容词", volume: "上册", grade: "六年级" },
    { word: "wrong", translation: "有毛病", explanation: "不正确的", pronunciation: "/rɒŋ/", category: "形容词", volume: "上册", grade: "六年级" },
    { word: "should", translation: "应该", explanation: "表示建议", pronunciation: "/ʃʊd/", category: "助动词", volume: "上册", grade: "六年级" },
    { word: "feel", translation: "觉得；感到", explanation: "有某种感觉", pronunciation: "/fiːl/", category: "动词", volume: "上册", grade: "六年级" },
    { word: "well", translation: "健康；身体好", explanation: "身体状况良好", pronunciation: "/wel/", category: "形容词", volume: "上册", grade: "六年级" },
    { word: "sit", translation: "坐", explanation: "坐下", pronunciation: "/sɪt/", category: "动词", volume: "上册", grade: "六年级" },
    { word: "grass", translation: "草坪", explanation: "草地", pronunciation: "/ɡrɑːs/", category: "植物", volume: "上册", grade: "六年级" },
    { word: "hear", translation: "听见", explanation: "用耳朵感知声音", pronunciation: "/hɪə/", category: "动词", volume: "上册", grade: "六年级" },
    { word: "ant", translation: "蚂蚁", explanation: "小昆虫", pronunciation: "/ænt/", category: "动物", volume: "上册", grade: "六年级" },
    { word: "worry", translation: "担心；担忧", explanation: "感到忧虑", pronunciation: "/ˈwʌri/", category: "动词", volume: "上册", grade: "六年级" },
    { word: "stuck", translation: "陷住；无法移动", explanation: "被卡住", pronunciation: "/stʌk/", category: "形容词", volume: "上册", grade: "六年级" },
    { word: "mud", translation: "泥", explanation: "湿土", pronunciation: "/mʌd/", category: "自然", volume: "上册", grade: "六年级" },
    { word: "pull", translation: "拉；拽", explanation: "用力拖拉", pronunciation: "/pʊl/", category: "动词", volume: "上册", grade: "六年级" },
    { word: "everyone", translation: "每人", explanation: "所有人", pronunciation: "/ˈevriˌwʌn/", category: "代词", volume: "上册", grade: "六年级" },

    // 六年级下册 Unit 3 - Where did you go?
    { word: "went", translation: "去（过去式）", explanation: "go的过去式", pronunciation: "/went/", category: "动词", volume: "下册", grade: "六年级" },
    { word: "camp", translation: "野营", explanation: "户外宿营", pronunciation: "/kæmp/", category: "活动", volume: "下册", grade: "六年级" },
    { word: "went camping", translation: "去野营（过去式）", explanation: "进行野营活动", pronunciation: "/went ˈkæmpɪŋ/", category: "短语", volume: "下册", grade: "六年级" },
    { word: "fish", translation: "钓鱼；捕鱼", explanation: "捕捉鱼类", pronunciation: "/fɪʃ/", category: "动词", volume: "下册", grade: "六年级" },
    { word: "went fishing", translation: "去钓鱼（过去式）", explanation: "进行钓鱼活动", pronunciation: "/went ˈfɪʃɪŋ/", category: "短语", volume: "下册", grade: "六年级" },
    { word: "rode", translation: "骑（过去式）", explanation: "ride的过去式", pronunciation: "/rəʊd/", category: "动词", volume: "下册", grade: "六年级" },
    { word: "hurt", translation: "受伤（过去式）", explanation: "hurt的过去式", pronunciation: "/hɜːt/", category: "动词", volume: "下册", grade: "六年级" },
    { word: "ate", translation: "吃（过去式）", explanation: "eat的过去式", pronunciation: "/eɪt/", category: "动词", volume: "下册", grade: "六年级" },
    { word: "took", translation: "拍照（过去式）", explanation: "take的过去式", pronunciation: "/tʊk/", category: "动词", volume: "下册", grade: "六年级" },
    { word: "took pictures", translation: "拍照（过去式）", explanation: "拍摄照片", pronunciation: "/tʊk ˈpɪktʃəz/", category: "短语", volume: "下册", grade: "六年级" },
    { word: "bought", translation: "买（过去式）", explanation: "buy的过去式", pronunciation: "/bɔːt/", category: "动词", volume: "下册", grade: "六年级" },
    { word: "gift", translation: "礼物", explanation: "赠送的物品", pronunciation: "/ɡɪft/", category: "物品", volume: "下册", grade: "六年级" },
    { word: "fell", translation: "摔倒（过去式）", explanation: "fall的过去式", pronunciation: "/fel/", category: "动词", volume: "下册", grade: "六年级" },
    { word: "off", translation: "从（某处）落下", explanation: "离开表面", pronunciation: "/ɒf/", category: "介词", volume: "下册", grade: "六年级" },
    { word: "Labour Day", translation: "劳动节", explanation: "五一劳动节", pronunciation: "/ˈleɪbə deɪ/", category: "节日", volume: "下册", grade: "六年级" },
    { word: "mule", translation: "骡子", explanation: "马和驴的杂交动物", pronunciation: "/mjuːl/", category: "动物", volume: "下册", grade: "六年级" },
    { word: "Turpan", translation: "吐鲁番", explanation: "新疆的一个城市", pronunciation: "/tʊəˈpæn/", category: "地名", volume: "下册", grade: "六年级" },
    { word: "could", translation: "能（过去式）", explanation: "can的过去式", pronunciation: "/kʊd/", category: "助动词", volume: "下册", grade: "六年级" },
    { word: "till", translation: "直到", explanation: "一直到某个时间", pronunciation: "/tɪl/", category: "介词", volume: "下册", grade: "六年级" },
    { word: "beach", translation: "海滩；沙滩", explanation: "海边的沙地", pronunciation: "/biːtʃ/", category: "地点", volume: "下册", grade: "六年级" },
    { word: "basket", translation: "篮；筐", explanation: "装东西的容器", pronunciation: "/ˈbɑːskɪt/", category: "物品", volume: "下册", grade: "六年级" },
    { word: "part", translation: "角色", explanation: "在戏剧中扮演的人物", pronunciation: "/pɑːt/", category: "表演", volume: "下册", grade: "六年级" },
    { word: "licked", translation: "舔（过去式）", explanation: "lick的过去式", pronunciation: "/lɪkt/", category: "动词", volume: "下册", grade: "六年级" },
    { word: "laughed", translation: "笑（过去式）", explanation: "laugh的过去式", pronunciation: "/lɑːft/", category: "动词", volume: "下册", grade: "六年级" },

    // 六年级下册 Unit 4 - Then and now
    { word: "dining hall", translation: "饭厅", explanation: "吃饭的大厅", pronunciation: "/ˈdaɪnɪŋ hɔːl/", category: "地点", volume: "下册", grade: "六年级" },
    { word: "grass", translation: "草地", explanation: "长草的地面", pronunciation: "/ɡrɑːs/", category: "自然", volume: "下册", grade: "六年级" },
    { word: "gym", translation: "体育馆", explanation: "运动场所", pronunciation: "/dʒɪm/", category: "地点", volume: "下册", grade: "六年级" },
    { word: "ago", translation: "以前", explanation: "过去的时间", pronunciation: "/əˈɡəʊ/", category: "时间", volume: "下册", grade: "六年级" },
    { word: "cycling", translation: "骑自行车运动", explanation: "骑车活动", pronunciation: "/ˈsaɪklɪŋ/", category: "运动", volume: "下册", grade: "六年级" },
    { word: "go cycling", translation: "去骑自行车", explanation: "进行骑车活动", pronunciation: "/ɡəʊ ˈsaɪklɪŋ/", category: "短语", volume: "下册", grade: "六年级" },
    { word: "ice-skate", translation: "滑冰", explanation: "在冰上滑行", pronunciation: "/ˈaɪs skeɪt/", category: "运动", volume: "下册", grade: "六年级" },
    { word: "badminton", translation: "羽毛球运动", explanation: "用球拍打羽毛球", pronunciation: "/ˈbædmɪntən/", category: "运动", volume: "下册", grade: "六年级" },
    { word: "star", translation: "星", explanation: "天空中的发光体", pronunciation: "/stɑː/", category: "自然", volume: "下册", grade: "六年级" },
    { word: "easy", translation: "容易的", explanation: "不困难的", pronunciation: "/ˈiːzi/", category: "形容词", volume: "下册", grade: "六年级" },
    { word: "look up", translation: "（在词典中或通过电脑）查阅", explanation: "查找信息", pronunciation: "/lʊk ʌp/", category: "短语", volume: "下册", grade: "六年级" },
    { word: "Internet", translation: "互联网", explanation: "全球网络", pronunciation: "/ˈɪntənet/", category: "科技", volume: "下册", grade: "六年级" },
    { word: "different", translation: "不同的", explanation: "有差别的", pronunciation: "/ˈdɪfrənt/", category: "形容词", volume: "下册", grade: "六年级" },
    { word: "active", translation: "积极的；活跃的", explanation: "很活泼的", pronunciation: "/ˈæktɪv/", category: "形容词", volume: "下册", grade: "六年级" },
    { word: "race", translation: "赛跑", explanation: "比赛跑步", pronunciation: "/reɪs/", category: "运动", volume: "下册", grade: "六年级" },
    { word: "nothing", translation: "没有什么", explanation: "什么都没有", pronunciation: "/ˈnʌθɪŋ/", category: "代词", volume: "下册", grade: "六年级" },
    { word: "thought", translation: "想（过去式）", explanation: "think的过去式", pronunciation: "/θɔːt/", category: "动词", volume: "下册", grade: "六年级" },
    { word: "felt", translation: "感觉（过去式）", explanation: "feel的过去式", pronunciation: "/felt/", category: "动词", volume: "下册", grade: "六年级" },
    { word: "cheetah", translation: "猎豹", explanation: "跑得很快的动物", pronunciation: "/ˈtʃiːtə/", category: "动物", volume: "下册", grade: "六年级" },
    { word: "trip", translation: "绊倒", explanation: "被东西绊住而跌倒", pronunciation: "/trɪp/", category: "动词", volume: "下册", grade: "六年级" },
    { word: "woke", translation: "醒（过去式）", explanation: "wake的过去式", pronunciation: "/wəʊk/", category: "动词", volume: "下册", grade: "六年级" },
    { word: "dream", translation: "梦", explanation: "睡觉时的幻象", pronunciation: "/driːm/", category: "名词", volume: "下册", grade: "六年级" }
]


// 导出数据供其他文件使用
if (typeof module !== 'undefined' && module.exports) {
    // Node.js 环境
    module.exports = {
        vocabulary: vocabulary
    };
} else {
    // 浏览器环境，将数据挂载到全局对象
    window.vocabulary = vocabulary;
}